### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by AokoAsami199** [Androz2091/discord-temp-channels#47]
i need a config file like config.json to setup the bot, guild, token,.....
I tried but it was error

**Comment by GlitchApotamus** [comment]
Just assign the variables in your index file. There is no config file for this as it's just for the npm package itself.

**Comment by retrouser955** [comment]
send ze error please 😃 we can't fix without the error

**Comment by AokoAsami199** [comment]
> Just assign the variables in your index file. There is no config file for this as it's just for the npm package itself.

how ????
can you explain carefully pls ???

**Comment by loveisglitchy** [comment]
Look at the example bot that is posted in the readme.
