### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by mariocmg** [Androz2091/discord-temp-channels#9]
How can I put it so that if the administrator leaves the channel does not close and if it remains empty it is eliminated? In the childAutoDeleteIfOwnerLeaves: false and childAutoDeleteIfEmpty: true; But when all the people leave the channel is not deleted

**Comment by krussedull** [comment]
same here accualy

**Comment by Androz2091** [comment]
Fixed in v2.0.0

**Comment by B1GBOOM420** [comment]
It is still an issue in V3.0.1 - btw @Androz2091
